settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: procloud-web # unique identifier
    name: www.procloud.cf
    description: 'ProCloud FrontEnd Server' # default=empty
    url: 'https://www.procloud.cf' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false

  - id: procloud-panel
    name: panel.procloud.cf
    description: 'ProClouds Panel'
    url: 'https://panel.procloud.cf/status'
    method: GET
    expectStatus: 200
   

  - id: node-eu
    name: Node Amsterdam Europe
    url: 'https://am.node.procloud.cf'
    method: GET
    expectStatus: 200
    
     - id: node-us
    name: Node New York USA
    url: 'https://us.node.procloud.cf'
    method: GET
    expectStatus: 200
    
     - id: node-ca
    name: Node Toronto Canada
    url: 'https://to.node.procloud.cf'
    method: GET
    expectStatus: 200
